import * as crypto from "crypto";
import { Router } from "express";
import { requireUser } from "./middleware/requireUser.js";
import { supabaseAdmin } from "./supabaseAdmin.js";
import { createIssue, getIssue } from "../../../src/jira/client.js";
import {
  markViolationTracked,
  buildViolationFingerprint,
  upsertViolations,
} from "./violationStore.js";
import { getUserJiraConfig, JiraDecryptError } from "./jiraConfig.js";
import { ARCH_RULESET_VERSION } from "../../../src/ai/critic.js";
import type { CriticViolation } from "../../../src/types.js";
import type { ArchGraph } from "../../../src/types.js";

const router = Router();

/** Params for creating a Jira ticket for one violation (used by route and chat). */
export interface TrackViolationParams {
  config: { baseUrl: string; email: string; apiToken: string };
  projectKey: string;
  violation: CriticViolation;
  projectRoot?: string;
  projectName?: string;
  workspaceId?: string;
  archModulePath?: string;
  archModuleFiles?: string[];
}

/** Result of tracking a single violation in Jira. */
export interface TrackViolationResult {
  key?: string;
  url?: string;
  existing?: boolean;
  error?: string;
}

/** Create a Jira ticket for one violation. Used by POST /jira-violation and chat "Track" handling. */
export async function createJiraTicketForViolation(
  params: TrackViolationParams
): Promise<TrackViolationResult> {
  const {
    config,
    projectKey,
    violation,
    projectRoot,
    projectName,
    workspaceId,
    archModulePath,
    archModuleFiles,
  } = params;
  const vSourceNodeId = violation.sourceNodeId;
  const vTargetNodeId = violation.targetNodeId;
  const vType = violation.type;
  const vSeverity = violation.severity;
  const vDescription = violation.description;
  const vSuggestedFix = violation.suggestedFix;

  let storedId: string | null = null;
  if (workspaceId && supabaseAdmin) {
    const raw = {
      type: vType,
      severity: vSeverity,
      sourceNodeId: vSourceNodeId,
      targetNodeId: vTargetNodeId,
      description: vDescription,
      suggestedFix: vSuggestedFix,
    };
    const upserted = await upsertViolations(supabaseAdmin, {
      workspaceId,
      violations: [raw],
      rulesVersion: ARCH_RULESET_VERSION,
    });
    const match = upserted.find(
      (r) =>
        r.source_node_id === vSourceNodeId &&
        r.target_node_id === (vTargetNodeId ?? null) &&
        r.type === vType
    );
    if (match?.id) storedId = match.id;
  }

  const repoName = repoNameFromPath(projectRoot ?? "");
  const labels = ["architecture", "littlelabs-auto"];
  if (repoName) labels.push(repoName);
  labels.push(`archNodeId:${vSourceNodeId}`.slice(0, 255));

  const modulePath = archModulePath ?? vSourceNodeId;
  const moduleFiles = Array.isArray(archModuleFiles) ? archModuleFiles : [];
  const fingerprint =
    modulePath && moduleFiles.length > 0
      ? computeModuleFingerprint(modulePath, moduleFiles)
      : null;

  const summaryBase = vType.replace(/_/g, " ");
  const pathPart = vTargetNodeId ? `${vSourceNodeId} → ${vTargetNodeId}` : vSourceNodeId;
  const summary = `[ARCH] ${summaryBase}: ${pathPart}`;

  const descriptionLines = [
    "## Architecture Violation — LittleLabs",
    "",
    `**Type:** ${summaryBase}`,
    `**Severity:** ${vSeverity.toUpperCase()}`,
    `**Detected:** ${new Date().toISOString()}`,
    projectName ? `**Project:** ${projectName}` : "",
    projectRoot ? `**Root:** ${projectRoot}` : "",
    "",
    "### What was found",
    vDescription ?? "",
    "",
    "### Affected node(s)",
    `- Source: \`${vSourceNodeId}\``,
    vTargetNodeId ? `- Target: \`${vTargetNodeId}\`` : "",
    "",
    vSuggestedFix ? `### Suggested fix\n${vSuggestedFix}` : "",
    fingerprint ? `arch-fingerprint: ${fingerprint}` : "",
    `arch-module: ${modulePath}`,
    "",
    "---",
    "*Auto-generated by LittleLabs Architecture Intelligence*",
  ].filter(Boolean);

  const description = descriptionLines.join("\n");

  try {
    const issue = await createIssue(
      { baseUrl: config.baseUrl, email: config.email, apiToken: config.apiToken },
      {
        projectKey,
        summary,
        description,
        labels,
        issueType: process.env.JIRA_ISSUE_TYPE ?? "Bug",
        priority: triagePriority(vSeverity),
      }
    );

    if (storedId && supabaseAdmin) {
      await markViolationTracked(supabaseAdmin, storedId, issue.key, "To Do");
    } else if (!storedId && workspaceId && supabaseAdmin) {
      const fp = buildViolationFingerprint(
        {
          type: vType,
          severity: vSeverity,
          sourceNodeId: vSourceNodeId,
          targetNodeId: vTargetNodeId,
        },
        ARCH_RULESET_VERSION
      );
      const { data: row } = await supabaseAdmin
        .from("violations")
        .select("id")
        .eq("workspace_id", workspaceId)
        .eq("fingerprint", fp)
        .eq("rules_version", ARCH_RULESET_VERSION)
        .maybeSingle();
      if (row?.id) {
        await markViolationTracked(supabaseAdmin, row.id, issue.key, "To Do");
      }
    }

    return {
      key: issue.key,
      url: `${config.baseUrl.replace(/\/$/, "")}/browse/${issue.key}`,
      existing: false,
    };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return { error: message };
  }
}

function computeModuleFingerprint(path: string, files: string[]): string {
  const payload = `${path}:${files.length}:${[...files].sort().join(",")}`;
  return crypto.createHash("sha256").update(payload).digest("hex").slice(0, 16);
}

function triagePriority(severity: string): string {
  const map: Record<string, string> = {
    critical: "Highest",
    high: "High",
    medium: "Medium",
    low: "Low",
  };
  return map[severity] ?? "Medium";
}

function repoNameFromPath(projectRoot: string): string | null {
  if (!projectRoot) return null;
  const parts = projectRoot.replace(/\\/g, "/").split("/").filter(Boolean);
  return parts[parts.length - 1] ?? null;
}

function isJiraOpen(status: string): boolean {
  return !/done|resolved|closed|complete/i.test(status);
}

async function getWorkspaceProjectKey(workspaceId: string | null): Promise<string | null> {
  if (!workspaceId || !supabaseAdmin) return null;
  const { data } = await supabaseAdmin
    .from("workspaces")
    .select("jira_project_key")
    .eq("id", workspaceId)
    .single();
  return (data as { jira_project_key?: string | null })?.jira_project_key ?? null;
}

router.post("/jira-violation", requireUser, async (req, res) => {
  let config;
  try {
    config = await getUserJiraConfig(req.user!.id);
  } catch (e) {
    if (e instanceof JiraDecryptError) {
      res.status(400).json({
        error: e.message,
        code: "jira_decrypt_failed",
      });
      return;
    }
    throw e;
  }
  if (!config) {
    res.status(400).json({
      error: "Jira is not connected. Use the Governance panel to connect your Jira account in the web app.",
    });
    return;
  }

  const { violationId, violation, projectRoot, projectName, workspaceId, archModulePath, archModuleFiles } = req.body as {
    violationId?: string;
    violation?: {
      type: string;
      severity: string;
      sourceNodeId: string;
      targetNodeId?: string;
      description?: string;
      suggestedFix?: string;
    };
    projectRoot?: string;
    projectName?: string;
    workspaceId?: string;
    archModulePath?: string;
    archModuleFiles?: string[];
  };

  const userId = req.user!.id;

  if (workspaceId && supabaseAdmin) {
    const { data: ws, error } = await supabaseAdmin
      .from("workspaces")
      .select("id")
      .eq("id", workspaceId)
      .eq("owner_id", userId)
      .single();
    if (error || !ws) {
      res.status(403).json({ error: "Workspace not found or access denied." });
      return;
    }
  }

  const projectKey =
    (await getWorkspaceProjectKey(workspaceId ?? null)) ?? config.project ?? null;
  if (!projectKey) {
    res.status(422).json({
      error: "project_key_required",
      message: "Set a project key in the sidebar to track violations in Jira.",
    });
    return;
  }

  let storedId: string | null = null;
  let existingJiraKey: string | null = null;
  let vType: string;
  let vSeverity: string;
  let vSourceNodeId: string;
  let vTargetNodeId: string | undefined;
  let vDescription: string | undefined;
  let vSuggestedFix: string | undefined;

  if (violationId && supabaseAdmin) {
    const { data: row, error } = await supabaseAdmin
      .from("violations")
      .select("*")
      .eq("id", violationId)
      .single();

    if (error || !row) {
      res.status(404).json({ error: "Violation not found" });
      return;
    }

    storedId = row.id;
    existingJiraKey = row.jira_key ?? null;
    vType = row.type;
    vSeverity = row.severity;
    vSourceNodeId = row.source_node_id;
    vTargetNodeId = row.target_node_id ?? undefined;
    vDescription = row.description ?? undefined;
    vSuggestedFix = row.suggested_fix ?? undefined;
  } else if (violation) {
    vType = violation.type;
    vSeverity = violation.severity;
    vSourceNodeId = violation.sourceNodeId;
    vTargetNodeId = violation.targetNodeId;
    vDescription = violation.description;
    vSuggestedFix = violation.suggestedFix;
    // Upsert so we have a row to mark tracked (chat-origin violations may not exist yet).
    if (workspaceId && supabaseAdmin) {
      const raw = {
        type: vType,
        severity: vSeverity,
        sourceNodeId: vSourceNodeId,
        targetNodeId: vTargetNodeId,
        description: vDescription,
        suggestedFix: vSuggestedFix,
      };
      const upserted = await upsertViolations(supabaseAdmin, {
        workspaceId,
        violations: [raw],
        rulesVersion: ARCH_RULESET_VERSION,
      });
      const match = upserted.find(
        (r) =>
          r.source_node_id === vSourceNodeId &&
          r.target_node_id === (vTargetNodeId ?? null) &&
          r.type === vType
      );
      if (match?.id) storedId = match.id;
    }
  } else {
    res.status(400).json({ error: "violationId or violation is required" });
    return;
  }

  if (existingJiraKey) {
    try {
      const existing = await getIssue(config, existingJiraKey);
      if (existing && isJiraOpen(existing.status)) {
        res.json({
          key: existingJiraKey,
          existing: true,
          status: existing.status,
        });
        return;
      }
    } catch {
      // ignore and fall through to create new ticket
    }
  }

  const violationObj: CriticViolation = {
    type: vType as CriticViolation["type"],
    severity: vSeverity as CriticViolation["severity"],
    sourceNodeId: vSourceNodeId,
    targetNodeId: vTargetNodeId,
    description: vDescription ?? "",
    suggestedFix: vSuggestedFix,
  };

  const result = await createJiraTicketForViolation({
    config,
    projectKey,
    violation: violationObj,
    projectRoot,
    projectName,
    workspaceId,
    archModulePath,
    archModuleFiles,
  });

  if (result.error) {
    res.status(500).json({ error: result.error });
    return;
  }
  res.json({
    key: result.key,
    url: result.url,
    existing: result.existing ?? false,
  });
});

export { router as jiraViolationRoutes };

