import * as fs from "fs";
import * as path from "path";
import type { RailId } from "../types";
import { getSandboxPath, ensureSandbox } from "./sandbox";

export interface MaterializationResult {
  success: boolean;
  copiedFiles: string[];
  error?: string;
}

export interface ProposedNodeSpec {
  id: string;
  label: string;
  layer?: string;
  archNodeId?: string;
  /** Optional skeleton code from designer; used as initial stub when present */
  skeletonCode?: string;
}

function isPathSafe(root: string, relPath: string): boolean {
  const resolved = path.resolve(root, relPath);
  const rootNorm = path.resolve(root);
  return resolved.startsWith(rootNorm) && resolved !== rootNorm;
}

/**
 * Write proposed greenfield nodes into a sandbox directory (folders + index.ts stubs).
 * Used so VERIFYING can run before copying to real project root.
 */
export function writeProposedNodesToSandbox(
  sandboxPath: string,
  nodes: ProposedNodeSpec[]
): { created: string[]; errors: string[] } {
  const created: string[] = [];
  const errors: string[] = [];
  const root = path.resolve(sandboxPath);

  for (const node of nodes) {
    const id = typeof node.id === "string" ? node.id : "";
    const label = typeof node.label === "string" ? node.label : id;
    const archNodeId = typeof node.archNodeId === "string" ? node.archNodeId : id;
    const relPath = id || archNodeId || label.replace(/\s+/g, "-").toLowerCase();

    if (!relPath || /\.\.|\\\\|\/\//.test(relPath)) {
      errors.push(`Invalid path for node ${label}: ${relPath}`);
      continue;
    }
    if (!isPathSafe(root, relPath)) {
      errors.push(`Path traversal blocked for ${label}`);
      continue;
    }

    try {
      const absPath = path.join(root, relPath);
      const pathLooksLikeFile = /\.(ts|tsx|js|jsx)$/.test(relPath);
      const targetDir = pathLooksLikeFile ? path.dirname(absPath) : absPath;

      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }

      const indexPath = pathLooksLikeFile ? absPath : path.join(absPath, "index.ts");
      const layer = typeof node.layer === "string" ? node.layer : "Uncategorized";
      const header =
        "// Generated by Arch Visualizer (sandbox). Boilerplate only.\n" +
        `// @archNodeId: ${archNodeId}`;
      const hasSkeleton =
        typeof node.skeletonCode === "string" && node.skeletonCode.trim().length > 0;
      const body = hasSkeleton
        ? `\n\n${node.skeletonCode!.trim()}\n`
        : `\n\n// TODO: Implement ${label} (${layer}).\n\nexport function TODO_${archNodeId.replace(
            /[^a-zA-Z0-9_]/g,
            "_"
          )}() {\n  // implementation pending\n}\n`;

      if (!fs.existsSync(indexPath)) {
        fs.writeFileSync(indexPath, `${header}${body}`, "utf-8");
      }
      const rel = path.relative(root, indexPath).replace(/\\/g, "/");
      created.push(rel);
    } catch (err) {
      errors.push(`${label}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  return { created, errors };
}

export function getRailSandboxPath(rootPath: string, railId: RailId): string {
  return getSandboxPath(rootPath, railId);
}

/**
 * Sync a set of project-relative paths from the real project root into the rail's sandbox.
 * This is used so verification (lint/tests/Playwright) can run against the sandbox.
 */
export function syncSandboxFromRoot(
  rootPath: string,
  railId: RailId,
  paths: string[]
): string {
  const sandboxRoot = ensureSandbox(rootPath, railId);
  for (const rel of paths) {
    const src = path.join(rootPath, rel);
    const dst = path.join(sandboxRoot, rel);
    try {
      if (!fs.existsSync(src)) continue;
      const dir = path.dirname(dst);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      fs.copyFileSync(src, dst);
    } catch {
      // Best-effort; verification will still run against whatever is present.
    }
  }
  return sandboxRoot;
}

export function materializeRail(
  railId: RailId,
  sandboxPath: string,
  rootPath: string
): MaterializationResult {
  const copiedFiles: string[] = [];
  try {
    const sandboxRoot = path.resolve(sandboxPath);
    const projectRoot = path.resolve(rootPath);

    if (!fs.existsSync(sandboxRoot)) {
      return { success: false, copiedFiles, error: `Sandbox for rail ${railId} does not exist` };
    }

    const entries = walkDir(sandboxRoot);
    for (const absFile of entries) {
      const rel = path.relative(sandboxRoot, absFile);
      const target = path.join(projectRoot, rel);
      const targetDir = path.dirname(target);
      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }
      fs.copyFileSync(absFile, target);
      copiedFiles.push(rel.replace(/\\/g, "/"));
    }

    return { success: true, copiedFiles };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { success: false, copiedFiles, error: message };
  }
}

function walkDir(root: string): string[] {
  const result: string[] = [];
  const stack: string[] = [root];
  while (stack.length > 0) {
    const current = stack.pop()!;
    const stat = fs.statSync(current);
    if (stat.isDirectory()) {
      const children = fs.readdirSync(current);
      for (const child of children) {
        stack.push(path.join(current, child));
      }
    } else if (stat.isFile()) {
      result.push(current);
    }
  }
  return result;
}

