/**
 * Generate Playwright spec content from greenfield acceptance criteria (functional).
 * Used in plan_node for greenfield rails so a spec file is available for humans/automation to run.
 */

import * as fs from "fs";
import * as path from "path";

const MAX_TEST_NAME_LEN = 80;

function truncateAtWord(text: string, maxLen: number): string {
  const safe = text.replace(/"/g, "'").trim();
  if (safe.length <= maxLen) return safe;
  const cut = safe.slice(0, maxLen);
  const lastSpace = cut.lastIndexOf(" ");
  return lastSpace > maxLen * 0.5 ? cut.slice(0, lastSpace) : cut;
}

function criterionToAssertion(c: string): string {
  const lower = c.toLowerCase().replace(/\n/g, " ");
  if (/\bbutton\b/.test(lower) || /\bclick\b/.test(lower)) {
    const match = c.match(/(?:button|click)\s+["']?([^"'\n]+)["']?/i) ?? c.match(/"([^"]+)"/);
    const label = match?.[1]?.trim() ?? lower.split(/\s+/).filter((w) => w.length > 3).slice(-2)[0] ?? "button";
    return `await expect(page.getByRole('button', { name: /${escapeRe(label)}/i })).toBeVisible();`;
  }
  if (/\blink\b/.test(lower)) {
    const match = c.match(/(?:link|to)\s+["']?([^"'\n]+)["']?/i) ?? c.match(/"([^"]+)"/);
    const label = match?.[1]?.trim() ?? lower.split(/\s+/).filter((w) => w.length > 3).slice(-2)[0] ?? "link";
    return `await expect(page.getByRole('link', { name: /${escapeRe(label)}/i })).toBeVisible();`;
  }
  if (/\bform\b/.test(lower)) {
    return `await expect(page.locator('form')).toBeVisible();`;
  }
  if (/\binput\b/.test(lower) || /\b(?:text|search)\s+field\b/.test(lower)) {
    return `await expect(page.getByRole('textbox').or(page.getByRole('searchbox')).first()).toBeVisible();`;
  }
  const words = lower.split(/\s+/).filter((w) => w.length > 2 && !/^(the|and|for|can|should|user|page|must|has|have|that|this|with|from|into)$/i.test(w));
  const phrase = words.slice(0, 4).join(" ");
  if (phrase) {
    return `await expect(page.getByText(/${escapeRe(phrase)}/i).first()).toBeVisible();`;
  }
  return `await expect(page.locator('body')).toBeVisible();`;
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function generatePlaywrightSpecFromCriteria(
  acceptanceCriteriaFunctional: string[],
  options: { specFileName?: string; baseUrl?: string } = {}
): string {
  const baseUrl = options.baseUrl
    ? `'${options.baseUrl.replace(/'/g, "\\'")}'`
    : "process.env.APP_URL ?? 'http://localhost:3000'";
  const criteria = acceptanceCriteriaFunctional.filter((c) => typeof c === "string" && c.trim());
  const blocks = criteria.map((c, i) => {
    const testName = truncateAtWord(c, MAX_TEST_NAME_LEN);
    const assertion = criterionToAssertion(c);
    return `  test('${i + 1}. ${testName}', async ({ page }) => {
    const response = await page.goto(${baseUrl});
    expect(response?.ok()).toBeTruthy();
    ${assertion}
  });`;
  });
  return `// Generated by Arch Visualizer from greenfield acceptance criteria. Do not edit by hand.
import { test, expect } from '@playwright/test';

test.describe('Greenfield acceptance (functional)', () => {
${blocks.join("\n\n")}
});
`;
}

/** Default spec path aligned with playwright.config.ts testDir (scripts/). */
const DEFAULT_SPEC_RELATIVE = "scripts/greenfield-generated.spec.ts";

/**
 * Write generated spec into the sandbox so a spec file exists for later execution.
 * Returns the absolute path of the written file.
 */
export function writeGeneratedSpecToSandbox(
  sandboxPath: string,
  acceptanceCriteriaFunctional: string[],
  specRelativePath: string = DEFAULT_SPEC_RELATIVE
): string {
  const content = generatePlaywrightSpecFromCriteria(acceptanceCriteriaFunctional);
  const fullPath = path.join(sandboxPath, specRelativePath);
  const dir = path.dirname(fullPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(fullPath, content, "utf-8");
  return path.resolve(fullPath);
}
